### ISSUE TITLE
How does this work asynchronously online?

### ISSUE THREAD

**Issue by abhigupta768** [shawon100/Online-Compiler#10]
I have played around with your implementation for quite some time now. Running it on the localhost does not let me parallelly process two different codes in say two separate browsers. The second request waits for the first one to complete.

Can you suggest why this does not happen online on the link provided by you and will it be the same if I deploy it online?

**Comment by abhigupta768** [comment]
So I dug deeper. In my view, what is happening is that the server configuration has multiple workers with multiple threads to handle simultaneous requests by different users. And for each user, we only need to run the script sequentially. So we don't need async capability for a basic implementation.

And the server handles different users through different instances by default, which is not happening in my localhost.

Am I correct?

**Comment by shawon100** [comment]
Yes. You are correct. You don't need to think about that. The loadbalancer of Cloud server will handle all kinds of traffics and loads.

**Comment by abhigupta768** [comment]
Thanks!
