### ISSUE TITLE
Not working on localhost server

### ISSUE THREAD

**Issue by vipul79321** [shawon100/Online-Compiler#5]
On running the online compiler on localhost, it is getting compiled properly but it is not showing any output, only verdict is shown. There might be some problem in c.php and c++11.php files in compiler folder.

**Comment by vipul79321** [comment]
@shawon100  can you help me out here?

**Comment by shawon100** [comment]
@vipul79321  you have to take permission. go to terminal and run chmod -R 777 your folder location

**Comment by vipul79321** [comment]
It worked thanks!!
