### ISSUE TITLE
Not able to get the output

### ISSUE THREAD

**Issue by anilneeluri** [shawon100/Online-Compiler#8]
when I try to execute a program, the output doesn't come up and it shows empty. Not even error

**Comment by shawon100** [comment]
did you give chmod -R 777 permission?

**Comment by anilneeluri** [comment]
Yes.

**Comment by shawon100** [comment]
in which folder you have applied the permission?

**Comment by anilneeluri** [comment]
I have put that in Html folder. There I have run the command " chmod -R 777 Online-Compiler"

**Comment by anilneeluri** [comment]
Can you help?
