### ISSUE TITLE
sh: javac: command not found

### ISSUE THREAD

**Issue by pranaylobo** [shawon100/Online-Compiler#9]
javac not working

**Comment by shawon100** [comment]
I have not installed java in my online server. But you can try in localhost. Your file name should be Main.java

**Comment by pranaylobo** [comment]
Yes I understand you have not in localhost it's working properly no.problem just like c c++,python2 I wanted Java and python3 to work online no localhost the point of openshift was without having any installed in users side you can access anything.In the pods terminal tell me how to access as admin then I can install Java packages

**Comment by shawon100** [comment]
You can not install from the pod terminal as it may not contain all features of terminal. You have to make your own pod or container with ubuntu os image  by docker and kubernetes and then add it to openshift. To do this you have to learn docker and kubernetes at first. Thanks.

**Comment by shawon100** [comment]
I have added Dockefile in this repository for creating custom image containers or pods and it will also install java compiler. If you have enough knowledge in docker and openshift you can deploy it.. Thanks.

**Comment by pranaylobo** [comment]
Thank you
